### ISSUE TITLE
App crashes when registering a new user (user is registered though)

### ISSUE THREAD

**Issue by mstein11** [happimeter/happimeter-watch#40]
When registering a new user on the login screen (just putting in credentials that don't belong to an existing user account) the app crashes.

Reason: The field "expires" now returns an int value and not a Datetime string anymore.

@paulputter: is it possible that this was caused by fixing an issue with the signup that was mentioned by joao gabriel recently? 

Will fix by allowing for an int value of "expires"

**Comment by mstein11** [comment]
already fixed

**Comment by paulputter** [comment]
Yes. :-)
